Repository Vactor0911/task-ez, pull requests merged in 2024-12, with the labels that each got.

#25 Hits
  src/components/FlexMenu.tsx
  src/components/LoginButton.tsx
  src/components/LoginModal.tsx
  src/components/RegisterModal.tsx
  src/state/index.ts
Labels: 개선

#27 작업 편집 대화상자 기능 구현
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/components/MyShowMoreModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
  src/utils/index.ts
Labels: 개선

#28 Dev
  src/components/FlexMenu.tsx
  src/components/Login.tsx
  src/components/LoginButton.tsx
  src/components/LoginModal.tsx
  src/components/Modal.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/components/MyShowMoreModal.tsx
  src/components/Register.tsx
  src/components/RegisterModal.tsx
  src/components/TaskModal.tsx
  src/pages/Main.tsx
  src/state/index.ts
  src/utils/index.ts
Labels: 개선

#29 loginStateAtom 변수명을 TaskEzLoginStateAtom 으로 변경
  src/components/FlexMenu.tsx
  src/components/LoginModal.tsx
  src/state/index.ts
Labels: 버그, 개선

#30 로컬 스토리지 변수 재수정
  src/components/FlexMenu.tsx
  src/components/LoginModal.tsx
  src/state/index.ts
Labels: 버그, 개선

#32 모달 대화상자 수정
  src/components/FlexMenu.tsx
  src/components/LoginButton.tsx
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/RegisterModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
Labels: 개선

#33 TaskModal 작업 저장 버튼 api 연결 및 구현
  src/components/TaskModal.tsx
Labels: 개선

#34 dev 코드 리뷰
  src/components/TaskModal.tsx
Labels: 개선, 오류 의심

#35 Dev
  src/components/FlexMenu.tsx
  src/components/LoginButton.tsx
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/RegisterModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
Labels: 개선

#39 검색 기능 추가
  src/components/FlexMenu.tsx
Labels: 개선

#40 day 3일전 알림 뜨기
  src/components/FlexMenu.tsx
Labels: 개선

#41 검색창 마진 수정, 알림창 스크롤바 , 영역지정 , 클릭시 모달창 , 글씨 위치 및 크기 수정
  src/components/FlexMenu.tsx
Labels: 개선

#42 백엔드에서 반환된 데이터 표시
  src/components/TaskModal.tsx
Labels: 개선

#43 D-day 오류 수정
  src/components/FlexMenu.tsx
Labels: 개선

#46 백엔드 통신 구현 및 오류 수정
  public/vite.svg
  src/components/FlexMenu.tsx
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/components/MyShowMoreModal.tsx
  src/components/PasswordSearch.tsx
  src/components/RegisterModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
  src/utils/index.ts
Labels: 버그, 개선

#47 Dev
  public/vite.svg
  src/components/FlexMenu.tsx
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/components/MyShowMoreModal.tsx
  src/components/PasswordSearch.tsx
  src/components/RegisterModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
  src/utils/index.ts
Labels: 개선

#52 확장 메뉴 리팩토링 및 비로그인 상태 조작 핸들링 수정
  src/components/FlexMenu.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
Labels: 개선

#54 Vactor0911
  package-lock.json
  package.json
  public/404.html
  src/App.tsx
  src/components/FlexMenu.tsx
  src/components/MyCalendar.tsx
  src/components/TaskModal.tsx
  src/pages/Main.tsx
  src/pages/Mobile.tsx
  vite.config.ts
Labels: 버그, 개선

#55 Dev
  package-lock.json
  package.json
  public/404.html
  src/App.tsx
  src/components/FlexMenu.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/components/TaskModal.tsx
  src/pages/Main.tsx
  src/pages/Mobile.tsx
  vite.config.ts
Labels: 버그, 개선

#56 오류 수정 및 디버깅
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/RegisterModal.tsx
  src/pages/Mobile.tsx
  src/state/index.ts
Labels: 버그

#57 Dev
  src/components/LoginModal.tsx
  src/components/MyCalendar.tsx
  src/components/RegisterModal.tsx
  src/pages/Mobile.tsx
  src/state/index.ts
Labels: 버그

#58 작업 알림 목록 필터링 알고리즘 수정
  src/components/FlexMenu.tsx
  src/utils/index.ts
Labels: 버그

#59 작업 알림 목록 필터링 알고리즘 수정
  src/components/FlexMenu.tsx
  src/utils/index.ts
Labels: 버그

#61 작업 검색 입력바 엔터키 입력 오류 수정
  src/components/FlexMenu.tsx
Labels: 버그

#62 작업 검색 입력바 엔터키 입력 오류 수정
  src/components/FlexMenu.tsx
Labels: 버그

#63 Shkim429
  README.md
Labels: 문서화

#64 README.md 파일 작성
  README.md
Labels: 문서화

#66 오류 수정 및 디버깅
  src/components/FlexMenu.tsx
  src/components/MyCalendarToolbar.tsx
  src/utils/index.ts
Labels: 버그

#67 한국 표준시 핸들링 오류 수정
  src/utils/index.ts
Labels: 버그

#68 한국 표준시 핸들링 오류 수정
  src/utils/index.ts
Labels: 버그

#69 숨겨진 작업 표시 대화상자 오류 수정
  src/components/MyCalendar.tsx
  src/components/MyEvent.tsx
  src/components/MyShowMore.tsx
  src/components/MyShowMoreModal.tsx
Labels: 버그

#70 Dev
  src/components/MyCalendar.tsx
  src/components/MyEvent.tsx
  src/components/MyShowMore.tsx
  src/components/MyShowMoreModal.tsx
Labels: 버그

#71 ShowMore 펼치기 오류 수정
  src/components/MyCalendar.tsx
  src/components/MyShowMore.tsx
Labels: 버그

#72 프로젝트명 표기 오류 수정
  index.html
  public/404.html
  src/components/FlexMenu.tsx
Labels: 버그

#73 프로젝트명 표기 오류 수정
  index.html
  public/404.html
  src/components/FlexMenu.tsx
Labels: 버그

#74 Readme update
  README.md
Labels: 문서화

#75 README.md 내용 수정
  README.md
Labels: 문서화

#76 README.md 내용 수정
  README.md
Labels: 문서화
