Repository Vactor0911/task-ez, pull requests merged in 2024-11, with the labels that each got.

#9 Costar
  src/components/FlexMenu.tsx
Labels: 개선

#10 Dev
  package-lock.json
  package.json
  src/App.tsx
  src/components/FlexMenu.tsx
  src/components/MyCalendar.tsx
  src/components/MyCalendarToolbar.tsx
  src/pages/Main.tsx
  src/state/index.ts
Labels: 개선

#13 react-big-calendar 기본 스타일 구성
  src/components/MyCalendar.tsx
Labels: 개선

#15 [개요]
  src/components/FlexMenu.tsx
Labels: 개선

#16 Jsukhen
  src/components/Login.tsx
  src/components/Modal.tsx
  src/components/MyCalendar.tsx
  src/components/PasswordSearch.tsx
  src/components/PopupModal.tsx
  src/components/Register.tsx
  src/utils/theme.ts
Labels: 개선

#17 커스텀 더보기 버튼 구현
  src/components/MyCalendar.tsx
  src/components/MyShowMore.tsx
  src/state/index.ts
Labels: 개선

#19 코드 복구 및 디버깅
  src/components/MyCalendar.tsx
  src/components/PopupModal.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
  src/utils/index.ts
Labels: 버그, 개선

#20 겹치는 함수 삭제
  src/components/MyCalendar.tsx
Labels: 버그

#21 Dev
  src/components/FlexMenu.tsx
  src/components/Login.tsx
  src/components/Modal.tsx
  src/components/MyCalendar.tsx
  src/components/MyShowMore.tsx
  src/components/PasswordSearch.tsx
  src/components/Register.tsx
  src/components/TaskModal.tsx
  src/state/index.ts
  src/utils/index.ts
  src/utils/theme.ts
Labels: 개선

#22 Jsukhen
  src/components/FlexMenu.tsx
  src/components/Login.tsx
  src/components/LoginModal.tsx
  src/components/Modal.tsx
  src/components/Register.tsx
  src/components/RegisterModal.tsx
  src/pages/Main.tsx
  src/state/index.ts
Labels: 개선
